### PR TITLE
Add NSXT sample for NAT and CGW firewall

### PR DESCRIPTION
**Pull request by triptiattavar**
CRUD Public IP
CRUD NAT Rule
CRUD Group
CRUD CGW Firewall

Signed-Off-By: Tripti Attavar <tattavar@vmware.com>

### CODE REVIEW

**Comment by tianhao64** [comment]
Looks good overall. 
1. Please fix the format issues: https://travis-ci.org/vmware/vsphere-automation-sdk-python/jobs/540959618
2. Would it be better to split the sample into multiple files for public ip, NAT, Group CGW separately, if they don't depend on each other?
3. Please add supported vCenter version on the top of the file. If these are M7, please use 6.8.7, e.g:  https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/oauth/exchange_access_id_token_for_saml.py#L15

**Comment by triptiattavar** [comment]
Thank you for your comments. I have taken care of them. Please review.

**Comment by tianhao64** [comment]
Thanks for addressing the comments. Are these APIs introduced in M7 (6.8.7)? I thought they were available before M7. Please put vCenter version where these APIs first introduced.

**Comment by triptiattavar** [comment]
Thanks for pointing it out. I have addressed them.

**Pull request merged**
