### PR TITLE
Add vsphere-automation-sdk-python to the simple index

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by anusha94** [comment]
@s0undt3ch 

Let me test this locally. I cannot directly merge this PR, as `lib/` and `setup.py` is updated using our internal pipeline and I will have to make changes there to keep the dependencies at their latest version

**Comment by s0undt3ch** [comment]
This did allow us(salt) to lock the requirements, however, I think I had the packages cached, because on a CI run, this didn't actually work.

For this to work, `setup.py` would have to be updated to use the package names(locking it to versions should work too) instead of local file paths.

**Comment by s0undt3ch** [comment]
But once `setup.py` is updated, it should be as simple as:
`pip install --extra-index-url=https://cdn.githubraw.com/vmware/vsphere-automation-sdk-python/master/lib/ vsphere-automation-sdk`

**Comment by ShadowJonathan** [comment]
Why was this PR closed?

**Pull request closed without merging**
