### PR TITLE
Adding New Sample to Delete User specified Virtual Machine

### PR DESCRIPTION
**Pull request by pgbidkar**
Signed-off-by: Pavan Bidkar <pbidkar@vmware.com>

### CODE REVIEW

**Comment by tianhao64** [comment]
Looks like there is some format issues. Can you check your format by running pep8?

**Comment by pgbidkar** [comment]
Fixed format issue.

**Comment by tianhao64** [comment]
I still get this:
(py36demo) het-m01:scripts het$ pep8 delete_vm.py
delete_vm.py:71:11: W292 no newline at end of file

**Comment by pgbidkar** [comment]
Added new line at the end of file. 
C:\Users\pbidkar\PycharmProjects\vsphere-automation-sdk-python\samples\vsphere\vcenter\vm>pep8 delete_vm.py

C:\Users\pbidkar\PycharmProjects\vsphere-automation-sdk-python\samples\vsphere\vcenter\vm>

**Pull request merged**
